In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Import Libaries Required

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Dataset
### Purpose: Extract raw dataset without modification

## 📂 Dataset Loading for Multiple Countries

### 🔹 Approach Used

The same code structure is reused for multiple countries by **only changing the file path** of the dataset. Each country has its own CSV file, and switching between datasets is done by updating the path accordingly.

```python
df = pd.read_csv("/content/drive/MyDrive/DVA_capstone/Raw_datasets/US_youtube_trending_data.csv")
```

---

### 🔹 Key Idea

- The logic remains **constant**
- Only the dataset path changes:
  - `US_youtube_trending_data.csv`
  - `IN_youtube_trending_data.csv`
  - `GB_youtube_trending_data.csv`
  - *etc.*

---

### ✅ Benefits

- **Code Reusability** → The same code works across all country datasets  
- **Consistency** → Ensures uniform data loading and structure  
- **Scalability** → Easily extendable to additional countries without modifying logic  

---

### 🎯 Summary

This approach simplifies dataset handling by separating **data location (file path)** from **processing logic**, making the workflow efficient, maintainable, and scalable for multi-country analysis.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/DVA_capstone/Raw_datasets/US_youtube_trending_data.csv")

 ## Initial Data Inspection

In [ ]:
df.shape

(268787, 16)

In [ ]:
df.sample(5)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
96324,MX_JCZYS31U,"Memphis Depay rescues Xavi, Barcelona at Villa...",2021-11-27T22:39:39Z,UC6c1z7bA__85CIWZ_jpCK-Q,ESPN FC,17,2021-12-01T00:00:00Z,barcelona|barca|villarreal|barcelona villarrea...,567910,7805,162,578,https://i.ytimg.com/vi/MX_JCZYS31U/default.jpg,False,False,"Frenkie de Jong, Memphis Depay and Philippe Co..."
1183,ua4QMFQATco,CGP Grey was WRONG,2020-08-11T17:15:11Z,UC2C_jShtL725hvbm1arSV9w,CGP Grey,27,2020-08-17T00:00:00Z,cgpgrey|education|hello internet,1670954,115658,1297,7987,https://i.ytimg.com/vi/ua4QMFQATco/default.jpg,False,False,‣ What Was TEKOI: https://www.youtube.com/watc...
206698,Dy68lCXLsGc,Starlink Mission,2023-06-04T12:32:41Z,UCtI0Hodo5o5dUb67FeUjDeA,SpaceX,28,2023-06-07T00:00:00Z,SpaceX|Space|Satellite|Mission|Starlink|Falcon 9,296830,12027,0,332,https://i.ytimg.com/vi/Dy68lCXLsGc/default.jpg,False,False,"SpaceX is targeting Sunday, June 4 at 8:20 a.m..."
113386,09AtdadKLL4,Mike Perry post-fight interview after beating ...,2022-02-20T05:01:21Z,UCmn9NOjiB3SaF8y6-X5GN9A,BroBible,24,2022-02-25T00:00:00Z,BroBible|sports|entertainment,546849,6899,0,1800,https://i.ytimg.com/vi/09AtdadKLL4/default.jpg,False,False,Subscribe to BroBible for More: https://goo.gl...
249716,nma-IJ5UF3A,Gypsy Rose's Shocking Truth Uncovered | The Pr...,2024-01-06T15:14:34Z,UCpYF_3dMxbTukeCG2GsgPbA,Lifetime,24,2024-01-11T00:00:00Z,lifetime|true crime|jail|prison|mysteries|docu...,434789,6059,0,581,https://i.ytimg.com/vi/nma-IJ5UF3A/default.jpg,False,False,Learn about Gypsy's early life with Munchausen...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268787 entries, 0 to 268786
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   video_id           268787 non-null  object
 1   title              268787 non-null  object
 2   publishedAt        268787 non-null  object
 3   channelId          268787 non-null  object
 4   channelTitle       268787 non-null  object
 5   categoryId         268787 non-null  int64
 6   trending_date      268787 non-null  object
 7   tags               268787 non-null  object
 8   view_count         268787 non-null  int64
 9   likes              268787 non-null  int64
 10  dislikes           268787 non-null  int64
 11  comment_count      268787 non-null  int64
 12  thumbnail_link     268787 non-null  object
 13  comments_disabled  268787 non-null  bool
 14  ratings_disabled   268787 non-null  bool
 15  description        264238 non-null  object
dtypes: bool(2), int64(5), object(9)
memory usage: 29.2+ MB

In [ ]:
df.describe()

          categoryId    view_count         likes       dislikes  comment_count
count  268787.000000  2.687870e+05  2.687870e+05  268787.000000   2.687870e+05
mean       18.743511  2.734467e+06  1.314697e+05    1134.277495   1.014303e+04
std         6.786562  9.794087e+06  4.539469e+05    8047.291315   7.260853e+04
min         1.000000  0.000000e+00  0.000000e+00       0.000000   0.000000e+00
25%        17.000000  4.725410e+05  1.796300e+04       0.000000   1.280000e+03
50%        20.000000  9.368710e+05  4.020500e+04       0.000000   2.754000e+03
75%        24.000000  2.106178e+06  9.877300e+04     467.000000   6.386000e+03
max        29.000000  1.407644e+09  1.602153e+07  879354.000000   6.738537e+06

In [ ]:
df.isnull().sum()

video_id                0
title                   0
publishedAt             0
channelId               0
channelTitle            0
categoryId              0
trending_date           0
tags                    0
view_count              0
likes                   0
dislikes                0
comment_count           0
thumbnail_link          0
comments_disabled       0
ratings_disabled        0
description          4549
dtype: int64

In [ ]:
df.isnull().mean()*100

video_id             0.000000
title                0.000000
publishedAt          0.000000
channelId            0.000000
channelTitle         0.000000
categoryId           0.000000
trending_date        0.000000
tags                 0.000000
view_count           0.000000
likes                0.000000
dislikes             0.000000
comment_count        0.000000
thumbnail_link       0.000000
comments_disabled    0.000000
ratings_disabled     0.000000
description          1.692418
dtype: float64

## HANDLE MISSING VALUES
### Purpose: Ensure no null issues in analytics

In [ ]:
df['description'] = df['description'].fillna('')
df['tags'] = df['tags'].fillna('')

##DROP IRRELEVANT COLUMNS
### Purpose: Remove non-analytical fields

In [ ]:
df.drop(['thumbnail_link'], axis=1, inplace=True)

## DATATYPE CONVERSION
### Purpose: Enable time-based analysis

In [ ]:
# Fix datetime
df['publish_time'] = pd.to_datetime(df['publishedAt'])
df.drop(['publishedAt'], axis=1, inplace=True)
df['trending_date'] = pd.to_datetime(df['trending_date'])

In [ ]:
df['comments_disabled'] = df['comments_disabled'].astype(int)
df['ratings_disabled'] = df['ratings_disabled'].astype(int)

In [ ]:
df['categoryId'] = df['categoryId'].astype('int8')
df['comments_disabled'] = df['comments_disabled'].astype('int8')
df['ratings_disabled'] = df['ratings_disabled'].astype('int8')

## REMOVE INVALID RECORDS
### Purpose: Ensure data quality

In [ ]:
df = df[df['view_count'] > 0]

## REMOVE DUPLICATES
### Purpose: Avoid duplicate daily entries

In [ ]:
df = df.drop_duplicates(subset=['video_id', 'trending_date'])

In [ ]:
df.shape

(264637, 15)

##FEATURE ENGINEERING
### Purpose: Create analytical metrics

In [ ]:
# Engagement metrics
df['engagement_rate'] = (
    df['likes'] + df['dislikes'] + df['comment_count']
) / df['view_count']
df['likes_ratio'] = df['likes'] / (df['likes'] + df['dislikes'] + 1)
df['comments_per_1000_views'] = df['comment_count'] / (df['view_count'] + 1) * 1000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264637 entries, 0 to 268786
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   video_id                 264637 non-null  object
 1   title                    264637 non-null  object
 2   channelId                264637 non-null  object
 3   channelTitle             264637 non-null  object
 4   categoryId               264637 non-null  int8
 5   trending_date            264637 non-null  datetime64[ns, UTC]
 6   tags                     264637 non-null  object
 7   view_count               264637 non-null  int64
 8   likes                    264637 non-null  int64
 9   dislikes                 264637 non-null  int64
 10  comment_count            264637 non-null  int64
 11  comments_disabled        264637 non-null  int8
 12  ratings_disabled         264637 non-null  int8
 13  description              264637 non-null  object
 14  publish_time             264637 non-null  datetime64[ns, UTC]
 15  engagement_rate          264637 non-null  float64
 16  likes_ratio              264637 non-null  float64
 17  comments_per_1000_views  264637 non-null  float64
dtypes: datetime64[ns, UTC](2), float64(3), int64(4), int8(3), object(6)
memory usage: 33.1+ MB

In [ ]:
# Time-based features
df['publish_hour'] = df['publish_time'].dt.hour
df['publish_day'] = df['publish_time'].dt.day_name()

In [ ]:
# Virality metric
df['days_to_trend'] = (
    df['trending_date']-
    df['publish_time']
).dt.days
df['days_to_trend'] = df['days_to_trend'].apply(lambda x: x if x >= 0 else 0)
df['virality_score'] = df['view_count'] / (df['days_to_trend'] + 1)

## Content Features
### Purpose: Analyse metadata and SEO strategy

In [ ]:
df['title_length'] = df['title'].apply(len)
df['tag_count'] = df['tags'].apply(lambda x: len(x.split('|')) if x != '[none]' else 0)

## TAG CLEANING - BASIC NORMALIZATION
### Purpose: Standardize tag format

In [ ]:
import re

def clean_tags(tags):
    if tags == '[none]' or tags == '':
        return ''

    tags = tags.lower()  # normalize case
    tags = tags.replace('|', ' ')  # replace separator

    # remove special characters
    tags = re.sub(r'[^a-zA-Z ]', '', tags)

    return tags

df['tags'] = df['tags'].apply(clean_tags)

## REMOVE DUPLICATE TAG WORDS
### Purpose: Avoid repetition like "music music song"

In [ ]:
def remove_duplicate_words(text):
    words = text.split()
    return ' '.join(set(words))

df['tags'] = df['tags'].apply(remove_duplicate_words)

## TAG COUNT FEATURE
### Purpose: Measure metadata richness

In [ ]:
df['tag_count']

0         15
1         25
2         30
3         23
4         33
          ..
268782     6
268783     1
268784     4
268785    22
268786    26
Name: tag_count, Length: 264637, dtype: int64

In [ ]:
df.sample(10)

,video_id,title,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,...,publish_time,engagement_rate,likes_ratio,comments_per_1000_views,publish_hour,publish_day,days_to_trend,virality_score,title_length,tag_count
120885,mZavtHhk508,Final Fantasy : Chaos Chronicles,UCsvn_Po0SmunchJYOWpOxMg,videogamedunkey,20,2022-04-04 00:00:00+00:00,chaos paradise ff xenoblade fantasy kill dunke...,2301077,151346,0,...,2022-03-31 19:00:25+00:00,0.069138,0.999993,3.366248,19,Thursday,3,5.752692e+05,32,21
190325,117LDel6VKw,'Naatu Naatu' Singers Kaala Bhairava & Rahul S...,UCZ8Sxmkweh65HetaZfR8YuA,The Hollywood Reporter,24,2023-03-17 00:00:00+00:00,entertainment rakshith naatu oscars prem bhair...,1435295,16600,0,...,2023-03-13 00:19:10+00:00,0.012001,0.999940,0.435450,0,Monday,3,3.588238e+05,99,14
239137,MPX5kmgVbN0,I Forced My Mum To Play Minecraft...,UC5p_l5ZeB_wGjO_yDXwiqvw,TommyInnit,20,2023-11-19 00:00:00+00:00,lose british play forced challenge video craft...,769393,115214,0,...,2023-11-13 21:30:08+00:00,0.156768,0.999991,7.021110,21,Monday,5,1.282322e+05,36,23
268535,JPg_6ZCngTU,I built a LEGO CRUISE SHIP...,UCUU3GdGuQshZFRGnxAPBf_w,TD BRICKS,24,2024-04-14 00:00:00+00:00,sacred build masters boat ship engineering bri...,11119948,99446,0,...,2024-04-05 19:04:55+00:00,0.009333,0.999990,0.390290,19,Friday,8,1.235550e+06,29,25
224693,sBLN0OxMK3M,USA 🇺🇸 vs Lithuania 🇱🇹 | J9 Highlights | FIBA ...,UCtInrnU3QbWqFGsdKT1GZtg,FIBA - The Basketball Channel,17,2023-09-07 00:00:00+00:00,highlights states ltu fiba world united usa ba...,1512991,13744,0,...,2023-09-03 15:27:46+00:00,0.010791,0.999927,1.706552,15,Sunday,3,3.782478e+05,71,14
37493,PnJpJBl4X_k,Skeppy vs BadBoyHalo UNDERWATER House Battle! ...,UCzMjRlKVO9XIqH_crIFpi6w,Skeppy,20,2021-02-19 00:00:00+00:00,cursing vs no build competition youtuber momen...,1519179,106367,1184,...,2021-02-14 00:34:22+00:00,0.075884,0.988982,5.088930,0,Sunday,4,3.038358e+05,57,33
133217,P8qUU-JZhP8,"Minecraft Manhunt, Truth or Lie",UC4gpVFHGncQNVzWLGVrEpZA,Boosfer,20,2022-06-05 00:00:00+00:00,into v poland enchants custom manhunt drops go...,184788,15003,0,...,2022-06-04 14:00:09+00:00,0.084670,0.999933,3.479644,14,Saturday,0,1.847880e+05,31,17
147549,gcPI6AfZqXs,VANTAGE is INSANELY OP in Apex Legends,UCfHweCd6pKP28kWNbI0wDig,Zylbrad,20,2022-08-15 00:00:00+00:00,legends zylbrad r funny highlights sniper paro...,330192,14565,0,...,2022-08-10 15:30:09+00:00,0.046903,0.999931,2.792306,15,Wednesday,4,6.603840e+04,38,16
139094,pfMQyms4OS0,17-Year-Old Returns Woman’s Lost Purse and Get...,UC9k-yiEpRHMNVOnOi_aQK8w,Inside Edition,25,2022-07-04 00:00:00+00:00,samaritan california chula purse teens returns...,5733147,244759,0,...,2022-06-29 20:51:28+00:00,0.044964,0.999996,2.272399,20,Wednesday,4,1.146629e+06,58,18
5461,9-6STGzbx6k,Lil Durk - The Voice (Official Music Video),UCaxOQZrF5llUMp-JjesUz1A,Lil Durk,10,2020-09-08 00:00:00+00:00,voice chicago durkio lil hip video smurkio fam...,3804501,147945,6385,...,2020-09-04 04:00:01+00:00,0.043657,0.958621,3.091863,4,Friday,3,9.511252e+05,43,14

## Flags
### Flag description presence and country for aggregations

In [ ]:
df['has_description'] = df['description'].apply(
    lambda x: False if pd.isna(x) or x.strip() == '' else True
)
df.drop(['description'], axis=1, inplace=True)

In [ ]:
df['country'] = 'US'

In [ ]:
df.isnull().sum()

video_id                   0
title                      0
channelId                  0
channelTitle               0
categoryId                 0
trending_date              0
tags                       0
view_count                 0
likes                      0
dislikes                   0
comment_count              0
comments_disabled          0
ratings_disabled           0
publish_time               0
engagement_rate            0
likes_ratio                0
comments_per_1000_views    0
publish_hour               0
publish_day                0
days_to_trend              0
virality_score             0
title_length               0
tag_count                  0
has_description            0
country                    0
dtype: int64

In [ ]:
# Rename for consistency
df.rename(columns={'view_count': 'views'}, inplace=True)
df.rename(columns={'tag_count': 'tags_count'}, inplace=True)

### Category Mapping

In [ ]:
category_map = {
    1: "Film & Animation",
    2: "Autos & Vehicles",
    10: "Music",
    15: "Pets & Animals",
    17: "Sports",
    18: "Short Movies",
    19: "Travel & Events",
    20: "Gaming",
    21: "Videoblogging",
    22: "People & Blogs",
    23: "Comedy",
    24: "Entertainment",
    25: "News & Politics",
    26: "Howto & Style",
    27: "Education",
    28: "Science & Technology",
    29: "Nonprofits & Activism",
    30: "Movies",
    31: "Anime/Animation",
    32: "Action/Adventure",
    33: "Classics",
    34: "Comedy",
    35: "Documentary",
    36: "Drama",
    37: "Family",
    38: "Foreign",
    39: "Horror",
    40: "Sci-Fi/Fantasy",
    41: "Thriller",
    42: "Shorts",
    43: "Shows",
    44: "Trailers"
}

In [ ]:
df['category_name'] = df['categoryId'].map(category_map)

In [ ]:
df['category_name'].isna().sum()

np.int64(0)

In [ ]:
df.drop(['categoryId'], axis=1, inplace=True)

In [ ]:
df['publish_day'] = df['publish_day'].astype('category')
df['country'] = df['country'].astype('category')

In [ ]:
# STANDARDIZE COLUMN NAMES (SNAKE_CASE)

df.rename(columns={
    'channelId': 'channel_id',
    'channelTitle': 'channel_title',
}, inplace=True)

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 264637 entries, 0 to 268786
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   video_id                 264637 non-null  object
 1   title                    264637 non-null  object
 2   channel_id               264637 non-null  object
 3   channel_title            264637 non-null  object
 4   trending_date            264637 non-null  datetime64[ns, UTC]
 5   tags                     264637 non-null  object
 6   views                    264637 non-null  int64
 7   likes                    264637 non-null  int64
 8   dislikes                 264637 non-null  int64
 9   comment_count            264637 non-null  int64
 10  comments_disabled        264637 non-null  int8
 11  ratings_disabled         264637 non-null  int8
 12  publish_time             264637 non-null  datetime64[ns, UTC]
 13  engagement_rate          264637 non-null  float64
 14  likes_ratio              264637 non-null  float64
 15  comments_per_1000_views  264637 non-null  float64
 16  publish_hour             264637 non-null  int32
 17  publish_day              264637 non-null  category
 18  days_to_trend            264637 non-null  int64
 19  virality_score           264637 non-null  float64
 20  title_length             264637 non-null  int64
 21  tags_count               264637 non-null  int64
 22  has_description          264637 non-null  bool
 23  country                  264637 non-null  category
 24  category_name            264637 non-null  object
dtypes: bool(1), category(2), datetime64[ns, UTC](2), float64(4), int32(1), int64(7), int8(2), object(6)
memory usage: 42.7+ MB

In [ ]:
# =========================================
# FINAL COLUMN ORDERING (DASHBOARD READY)
# =========================================

df = df[[
    # 🔹 1. IDENTIFIERS
    'video_id',
    'title',
    'channel_id',
    'channel_title',
    'category_name',

    # 🔹 2. TIME (RAW + DERIVED)
    'publish_time',
    'publish_hour',
    'publish_day',
    'trending_date',

    # 🔹 3. PERFORMANCE (RAW METRICS)
    'views',
    'likes',
    'comment_count',
    'comments_per_1000_views',
    'dislikes',

    # 🔹 4. ENGAGEMENT METRICS
    'likes_ratio',
    'engagement_rate',

    # 🔹 5. VIRALITY & GROWTH
    'days_to_trend',
    'virality_score',

    # 🔹 6. CONTENT FEATURES
    'tags',
    'tags_count',
    'has_description',

    # 🔹 7. FLAGS
    'comments_disabled',
    'ratings_disabled',
    'title_length',

    # 🔹 8. COUNTRY
    'country'
]]

In [ ]:
df.to_csv('/content/drive/MyDrive/DVA_capstone/Clean_datasets/us_clean.csv', index=False)